# Generated by Django 6.0.2 on 2026-03-18 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_direction', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'direction',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FunctionPosition',
            fields=[
                ('id_function', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'function_position',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id_organization', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('training_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='DZD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_direction', models.ForeignKey(db_column='id_direction', on_delete=django.db.models.deletion.CASCADE, to='Formation.direction')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('recruitment_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Executive', 'Executive'), ('Supervision', 'Supervision'), ('Execution', 'Execution')], max_length=20)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Retired', 'Retired'), ('On_Leave', 'On Leave')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_department', models.ForeignKey(db_column='id_department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formation.department')),
                ('id_direction', models.ForeignKey(db_column='id_direction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formation.direction')),
                ('id_function', models.ForeignKey(db_column='id_function', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formation.functionposition')),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id_catalog', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_link', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('training_start_date', models.DateField()),
                ('training_end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_organization', models.ForeignKey(db_column='id_organization', on_delete=django.db.models.deletion.CASCADE, to='Formation.organization')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['-exercise_year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Formation_Service', 'Formation Service'), ('Department_Head', 'Department Head'), ('Director', 'Director'), ('Employee', 'Employee'), ('Admin_Service_Formation', 'Admin Service Formation')], max_length=30)),
                ('first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('can_view_all_employees', models.BooleanField(default=False)),
                ('can_manage_catalogs', models.BooleanField(default=False)),
                ('can_approve_registrations', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('id_employee', models.OneToOneField(db_column='id_employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Formation.employee')),
                ('managed_department', models.ForeignKey(db_column='managed_department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='Formation.department')),
                ('managed_direction', models.ForeignKey(db_column='managed_direction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_by', to='Formation.direction')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id_training', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_hours', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('sessions_number', models.IntegerField(default=1)),
                ('recurrence_years', models.IntegerField(default=3)),
                ('custom_training_start_date', models.DateField(blank=True, null=True)),
                ('custom_training_end_date', models.DateField(blank=True, null=True)),
                ('training_type', models.CharField(choices=[('Recruitment', 'Recruitment'), ('Enhancement', 'Enhancement'), ('Reconversion', 'Reconversion'), ('Professional_Internship', 'Professional Internship'), ('Integration', 'Integration'), ('Corporate', 'Corporate')], max_length=30)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('code', models.CharField(choices=[('CDI', 'Cdi'), ('CDA', 'Cda'), ('CDF', 'Cdf'), ('CDJ', 'Cdj'), ('LDA', 'Lda'), ('LDC', 'Ldc')], max_length=10)),
                ('mode', models.CharField(choices=[('Remote', 'Remote'), ('In_Person', 'In Person'), ('Blended', 'Blended'), ('On_Job_Training', 'On Job Training')], max_length=20)),
                ('source', models.CharField(choices=[('Strategic', 'Strategic'), ('Supplier', 'Supplier'), ('Regulatory', 'Regulatory'), ('New_Received', 'New Received'), ('Structure', 'Structure'), ('Career_Evolution', 'Career Evolution')], max_length=20)),
                ('domain', models.CharField(choices=[('Technical', 'Technical'), ('Management', 'Management'), ('IT', 'It'), ('Safety', 'Safety'), ('Quality', 'Quality'), ('HSE', 'Hse'), ('Finance', 'Finance'), ('HR', 'Hr')], max_length=20)),
                ('nature', models.CharField(choices=[('Upgrade', 'Upgrade'), ('Certified', 'Certified'), ('Qualifying', 'Qualifying'), ('Diploma', 'Diploma'), ('Specific', 'Specific'), ('Training_Path', 'Training Path')], max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_catalog', models.ForeignKey(db_column='id_catalog', on_delete=django.db.models.deletion.CASCADE, to='Formation.catalog')),
                ('published_by', models.ForeignKey(db_column='published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id_registration', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_year', models.IntegerField()),
                ('objective', models.TextField(blank=True, null=True)),
                ('dept_head_validation', models.SmallIntegerField(default=0)),
                ('dept_head_observations', models.TextField(blank=True, null=True)),
                ('dept_head_date', models.DateTimeField(blank=True, null=True)),
                ('director_validation', models.SmallIntegerField(default=0)),
                ('director_observations', models.TextField(blank=True, null=True)),
                ('director_date', models.DateTimeField(blank=True, null=True)),
                ('formation_validation', models.SmallIntegerField(default=0)),
                ('formation_observations', models.TextField(blank=True, null=True)),
                ('formation_date', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='Formation.employee')),
                ('id_training', models.ForeignKey(db_column='id_training', on_delete=django.db.models.deletion.CASCADE, to='Formation.training')),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registrations', to=settings.AUTH_USER_MODEL)),
                ('dept_head_id', models.ForeignKey(db_column='dept_head_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_as_dept_head', to=settings.AUTH_USER_MODEL)),
                ('director_id', models.ForeignKey(db_column='director_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_as_director', to=settings.AUTH_USER_MODEL)),
                ('formation_id', models.ForeignKey(db_column='formation_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_as_formation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_catalogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catalog',
            name='published_by',
            field=models.ForeignKey(db_column='published_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_catalogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id_audit', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(max_length=100)),
                ('pc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('id_user', models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit',
                'ordering': ['-action_timestamp'],
            },
        ),
    ]
